#!/bin/bash

FILES=`git ls-tree --name-only HEAD .`
MAXLEN_FILE=0

for f in $FILES; do
    if [ ${#f} -gt $MAXLEN_FILE ]; then
        MAXLEN_FILE=${#f}
    fi
done

for f in $FILES; do
# f : file name - padded with printf
# str : timestamp
# str2 : all the fuck
    str=$(git log -1 --decorate --pretty=format:"%C(green)%cr%Creset" $f)
    str2=$(git log -1 --decorate --pretty=format:"%C(cyan)%h%Creset %C(yellow)(%cn)%Creset" $f)
    commitMsg=$(git log -1 --decorate --pretty=format:"%s" $f)
    printf "%-${MAXLEN_FILE}s -- %s \t %-42s %s\n" "$f" "$str" "$str2" "$commitMsg"
done
