#!/usr/bin/env python

# sudoers: nodraak ALL=NOPASSWD:/home/nodraak/.config/i3/kbdbacklight

import sys

FILEPATH='/sys/class/leds/smc::kbd_backlight/brightness'

def usage():
    print('Usage: %s inc|dec <value>' % sys.argv[0])
    exit(0)

def main():
    if (len(sys.argv) != 3) or (sys.argv[1] not in ('inc', 'dec')):
        usage()
    try:
        change = int(sys.argv[2])
        change *= 1 if sys.argv[1] == 'inc' else -1
    except ValueError:
        usage()

    with open(FILEPATH, 'r+') as f:
        val = int(f.read()) + change
        val = val if val >= 0 else 0
        val = val if val <= 255 else 255
        f.write('%d' % val)

main()

