#!/usr/bin/env bash

cd $(dirname $(realpath $0))

scrot -e 'mv $f lockbg.png'
convert lockbg.png \
    -blur 15x15 \
    -family Hack -fill '#FFFFFF' -stroke black -strokewidth 1 -pointsize 32 \
    -gravity south -annotate +0+200 'Type password to unlock' \
    debian.png -geometry +0+0 -composite lockbg.png

i3lock -e -t -i lockbg.png

# prevent possible race conditions with suspend
sleep 1
