#!/usr/bin/env bash

cd $(dirname $(realpath $0))

scrot -e 'mv $f _lockbg.png'
convert _lockbg.png \
    -blur 15x15 \
    -family Hack -fill '#FFFFFF' -stroke black -strokewidth 1 -pointsize 32 \
    -gravity south -annotate +0+200 'Type password to unlock' \
    debian.png -geometry +0+0 -composite _lockbg.png

i3lock -e -t -f -i _lockbg.png
