#!/usr/bin/env bash

cd $(dirname $(realpath $0))

scrot -e 'mv $f lockbg.png'
convert -blur 15x15 lockbg.png lockbg.png
convert \
    -family Hack -fill '#808080' -pointsize 28 -gravity center \
    -annotate +0+250 'Type password to unlock' \
    lockbg.png lockbg.png

i3lock -e -t -i lockbg.png

# prevent possible race conditions with suspend
sleep 1
