#!/bin/sh

DATA="$(curl --silent -w "\n%{http_code}\n" "https://httpbin.org/ip")"

STATUS_CODE="$(echo "${DATA}" | tail -n 1)"
if [ "${STATUS_CODE}" = "200" ]
then
    IP=$(echo "${DATA}" | sed -n "2p" | cut -d "\"" -f 4)

    echo "$IP"
    echo "$IP"
else
    echo "unknown (${STATUS_CODE})"
    echo "unknown (${STATUS_CODE})"
fi

