#!/usr/bin/env bash

DATA=$(amixer get Master | tail -n 1)
VOL=$(echo $DATA | grep -E -o '[0-9]+%')
MUT=$(echo $DATA | grep -E -o 'off')

if [ "$MUT" == "off" ]
then
    # full_text / short_text / color
    echo "MUT ($VOL)"
    echo "MUT ($VOL)"
    echo \#00C000
else
    echo $VOL
    echo $VOL
    if [ "$VOL" == "0%" ]
    then
        echo \#00C000
    fi
fi

